trigger:
  branches:
    include:
      - develop  # Only trigger on the develop branch

pool:
  vmImage: 'ubuntu-latest'  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build Astro project'

- task: CopyFiles@2
  inputs:
    Contents: |
      dist/**         # Astro builds to 'dist' by default
      package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy build files'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS-Service-Connection'
    regionName: 'me-central-1'  # Change to your region
    command: 's3'
    arguments: 'sync $(Build.SourcesDirectory) s3://jinglepay-website-dev --delete'
