trigger:
  branches:
    include:
      - develop  # Only trigger on the develop branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build Astro project'

- task: CopyFiles@2
  inputs:
    Contents: |
      dist/**         # Astro builds to 'dist' by default
      package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy build files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publish build artifacts'
