trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'ubuntu-latest'  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build Astro project'
  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    Contents: '**'          # Copy all files within the dist folder
    TargetFolder: '$(Build.ArtifactStagingDirectory)/dist'
  displayName: 'Copy root dist folder'
  
- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS_PROD'
    regionName: 'me-central-1'
    bucketName: 'jinglepay-website'
    sourceFolder: '$(Build.ArtifactStagingDirectory)/dist'
    targetFolder: ''
    flattenFolders: false

