# In the Astro site's repository (pipeline definition)

resources:
  repositories:
    - repository: gatsbyRepo # Alias for the Gatsby repository
      type: git # Or github, azureRepos, etc.
      name: JinglePay/jp_website # Project/Repository name (Adjust as needed)
      ref: main # Or the branch you want to build from the Gatsby repo

trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
# --- Checkout Self (Astro Repo - Implicit) ---
# By default, the repo containing the YAML is checked out as 's'
# Or uncomment below for clarity:
# - checkout: self
#   path: s # Default path

# --- Checkout Gatsby Repo ---
  - checkout: gatsbyRepo # Use the alias defined in resources
    path: gatsby # Checkout Gatsby repo into a 'gatsby' subdirectory within the agent's work folder

# --- Astro Steps ---
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Install Node.js for Astro'

  - script: |
      npm install
    displayName: 'Install Astro dependencies'
    workingDirectory: $(Pipeline.Workspace)/s # Default checkout path for self

  - bash: |
      echo "Determining Site URL based on branch: $(Build.SourceBranchName)"
      if [ "$(Build.SourceBranchName)" == "main" ]; then
        SITE_URL="https://jinglepay.com" # Production URL
      else
        SITE_URL="http://jinglepay-website-dev.s3-website.me-central-1.amazonaws.com" # Staging URL
      fi
      
      mkdir -p $(Pipeline.Workspace)/s/src
      
      echo "export const siteBaseUrl = '${SITE_URL}';" > $(Pipeline.Workspace)/s/src/siteConfig.js
      
      cat $(Pipeline.Workspace)/s/src/siteConfig.js
    displayName: 'Generate Astro src/siteConfig.js'
    workingDirectory: $(Pipeline.Workspace)/s

  - script: |
      npm run build
    displayName: 'Build Astro project'
    workingDirectory: $(Pipeline.Workspace)/s

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Pipeline.Workspace)/s/dist'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/astro-dist'
    displayName: 'Copy Astro build files'

# --- Gatsby Steps ---
  - task: NodeTool@0 # Install Node again if needed, or ensure version compatibility
    inputs:
      versionSpec: '18.x' # Or the Node version required by Gatsby
    displayName: 'Install Node.js for Gatsby'

  - script: |
      npm install
    displayName: 'Install Gatsby dependencies'
    workingDirectory: $(Pipeline.Workspace)/gatsby # Path where Gatsby repo was checked out

  - script: |
      npx gatsby build
    displayName: 'Build Gatsby project'
    workingDirectory: $(Pipeline.Workspace)/gatsby # Path where Gatsby repo was checked out

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Pipeline.Workspace)/gatsby/public' # Gatsby output folder relative to checkout path
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/gatsby-dist'
    displayName: 'Copy Gatsby build files'

# --- Publish Artifacts ---
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'websites-output'
    displayName: 'Publish build artifacts'

# --- Deploy Steps (DEV) ---
  - task: S3Upload@1
    condition: eq(variables['Build.SourceBranchName'], 'develop') # Condition based on Astro repo branch
    inputs:
      awsCredentials: 'AWS_DEV'
      regionName: 'me-central-1'
      bucketName: 'jinglepay-website-dev'
      sourceFolder: '$(Build.ArtifactStagingDirectory)/astro-dist'
      targetFolder: ''
      flattenFolders: false
    displayName: 'Deploy Astro to DEV S3 bucket (Root)'

  - task: S3Upload@1
    condition: eq(variables['Build.SourceBranchName'], 'develop') # Condition based on Astro repo branch
    inputs:
      awsCredentials: 'AWS_DEV'
      regionName: 'me-central-1'
      bucketName: 'jinglepay-website-dev'
      sourceFolder: '$(Build.ArtifactStagingDirectory)/gatsby-dist'
      targetFolder: 'are/en'
      flattenFolders: false
    displayName: 'Deploy Gatsby to DEV S3 bucket (are/en)'

# --- Deploy Steps (PROD) ---
  - task: S3Upload@1
    condition: eq(variables['Build.SourceBranchName'], 'main') # Condition based on Astro repo branch
    inputs:
      awsCredentials: 'AWS_PROD'
      regionName: 'me-central-1'
      bucketName: 'jinglepay-website'
      sourceFolder: '$(Build.ArtifactStagingDirectory)/astro-dist'
      targetFolder: ''
      flattenFolders: false
    displayName: 'Deploy Astro to PROD S3 bucket (Root)'

  - task: S3Upload@1
    condition: eq(variables['Build.SourceBranchName'], 'main') # Condition based on Astro repo branch
    inputs:
      awsCredentials: 'AWS_PROD'
      regionName: 'me-central-1'
      bucketName: 'jinglepay-website'
      sourceFolder: '$(Build.ArtifactStagingDirectory)/gatsby-dist'
      targetFolder: 'are/en'
      flattenFolders: false
    displayName: 'Deploy Gatsby to PROD S3 bucket (are/en)'
